version: '3.7'
services:
  university_app:
    image: denyskry/university_cms
    container_name: university_cms
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/university_schedule_app
    depends_on:
      - postgres
    networks:
      - backend
  postgres:
    container_name: postgres
    image: postgres:14.5-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: university_schedule_app
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5435:5432"
    networks:
      backend:
        aliases:
          - "postgres"
volumes:
  postgres:

networks:
  backend:
    driver: bridge
